# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: idawud.ShelfMD
PackageVersion: 2.0.0
PackageLocale: en-US
Publisher: idawud
PublisherUrl: https://github.com/idawud
PublisherSupportUrl: https://github.com/idawud/ShelfMD/issues
Author: idawud
PackageName: ShelfMD
PackageUrl: https://github.com/idawud/ShelfMD
License: MIT
LicenseUrl: https://github.com/idawud/ShelfMD/blob/main/LICENSE
Copyright: Copyright (c) 2026 Idawud
ShortDescription: Markdown book reader
Description: Read multi-file Markdown books with cross-file links, reading memory, and beautiful typography.
Moniker: shelfmd
Tags:
- markdown
- markdown-editor
- markdown-viewer
ReleaseNotes: |-
  What's Changed
  - chore(release): bump version to v2.0.0 by @github-actions[bot] in #24
  New Contributors
  - @github-actions[bot] made their first contribution in #24
  Full Changelog: v1.0.0...v2.0.0
ReleaseNotesUrl: https://github.com/idawud/ShelfMD/releases/tag/v2.0.0
ManifestType: defaultLocale
ManifestVersion: 1.12.0
